apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: "auth-service"
  name: "auth-service"
  namespace: "#{EKS_NAMESPACE}#"
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0      
  selector: 
    matchLabels: 
      app: "auth-service"
  template:
    metadata:
      labels:
        app: "auth-service"
    spec: 
      containers: 
        - image: "your-ecr-registry-url/auth-service:#{IMAGE_TAG}#"
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: "auth-service"
          name: "auth-service"
          ports: 
            - containerPort: 80
          resources:
            requests:
              memory: 200Mi
              cpu: 50m
            limits:
              memory: 512Mi
              cpu: 100m
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3             